name: Tag Version

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci
    - run: npm link
    - name: Bump a semantic version
      id: bump-semver
      run: echo "::set-output name=VERSION::$(git bump)"
    - name: Set Git user configs
      run: |
        git config --local user.name "CI - Tag Version"
        git config --local user.email "rinse@neko2.net"
    - name: Put a tag
      run: git tag -a ${{ steps.bump-semver.outputs.version }} -m "Release a version"
    - name: Push a Git tag
      run: git push origin ${{ steps.bump-semver.outputs.version }}
